name: lint-test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  # Run linter and tests against JS, TS, and YAML files
  linttestdeno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623 # v1.1.3
        with:
          deno-version: v1.38.0

      - name: fmt
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test
        run: |
          deno test --ignore=./json-config-jest \
            --allow-env --allow-read --allow-net \
            --junit-path=./report.xml
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: report
        uses: mikepenz/action-junit-report@75b84e78b3f0aaea7ed7cf8d1d100d7f97f963ec # v4.0.0
        if: always()
        with:
          report_paths: "report.xml"
          check_name: "deno test report"

  linttestjest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: "lts/*"

      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: install dependencies
        working-directory: "./json-config-jest"
        run: pnpm install --frozen-lockfile

      - name: lint
        working-directory: "./json-config-jest"
        run: pnpm lint

      - name: test
        working-directory: "./json-config-jest"
        run: pnpm test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: report
        uses: mikepenz/action-junit-report@75b84e78b3f0aaea7ed7cf8d1d100d7f97f963ec # v4.0.0
        if: always()
        with:
          report_paths: "./json-config-jest/junit.xml"
          check_name: "jest test report"
