name: mirror-bitbucket

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  # Mirror the main branch to BitBucket.
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: add bitbucket remote
        run: |
          git remote add bitbucket "https://x-token-auth:${BITBUCKET_ACCESS_TOKEN}@bitbucket.org/fensak-io/fensak-rules-examples.git"
          git fetch bitbucket
        env:
          BITBUCKET_ACCESS_TOKEN: ${{ secrets.BITBUCKET_ACCESS_TOKEN }}

      - name: push main branch
        run: git push bitbucket main
